parameters:
    oxid_esales.rate_limiter.enabled: true
    oxid_esales.rate_limiter.limit: 1
    oxid_esales.rate_limiter.interval: 60
    oxid_esales.rate_limiter.policy: 'token_bucket'
    oxid_esales.rate_limiter.excluded_routes: 
      - 'api/products'
    

services:
  _defaults:
    public: false
    autowire: true

  OxidSupport\RestApi\Controller\Api\ProductApiController:
    public: true

  OxidSupport\RestApi\Service\ProductServiceInterface:
    class: OxidSupport\RestApi\Service\ProductService
    public: true